import type { Metadata } from 'next';
import './globals.css';
import HydrationGate from '@/common/components/HydrationGate';
import ModalHost from '@/modules/ui/components/ModalHost';
import ClientProviders from '@/modules/formbuilder/components/ClientProviders';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <HydrationGate>
          <ClientProviders>
            <div className="w-full h-dvh ">{children}</div>
            <ModalHost />
          </ClientProviders>
        </HydrationGate>
      </body>
    </html>
  );
}
