import type { Metadata } from 'next';
import './globals.css';
import NextToploader from 'nextjs-toploader';
import DesignerContextProvider from '@/context/designer/DesignerProvider';
import ClientProviders from '@/components/ClientProviders';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NextToploader />
        <DesignerContextProvider>
          <ClientProviders>
            <div className="w-screen h-screen">{children}</div>
          </ClientProviders>
        </DesignerContextProvider>
      </body>
    </html>
  );
}
