import type { Metadata } from 'next';
import './globals.css';
import DesignerContextProvider from '@/context/designer/DesignerProvider';
import ClientProviders from '@/components/ClientProviders';
import HydrationGate from '@/common/components/HydrationGate';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <HydrationGate>
          <DesignerContextProvider>
            <ClientProviders>
              <div className="w-screen h-screen">{children}</div>
            </ClientProviders>
          </DesignerContextProvider>
        </HydrationGate>
      </body>
    </html>
  );
}
