import { formType } from './form.types';

export const MOCK_FORMS: formType[] = [
  {
    id: 'f-01',
    name: 'Customer Feedback (Q4)',
    description: 'NPS + short comment',
    createdAt: new Date('2025-10-18T10:12:00Z'),
    published: true,
    visits: 1240,
    submissions: 387,
  },
  {
    id: 'f-02',
    name: 'Bug Report',
    description: 'Capture repro steps and screenshots',
    createdAt: new Date('2025-09-02T14:30:00Z'),
    published: true,
    visits: 812,
    submissions: 196,
  },
  {
    id: 'f-03',
    name: 'Job Application',
    description: 'Basic applicant info',
    createdAt: new Date('2025-08-11T08:00:00Z'),
    published: false,
    visits: 95,
    submissions: 0,
  },
  {
    id: 'f-04',
    name: 'Internal Survey – UI Library',
    description: 'Vote on shadcn components to add',
    createdAt: new Date('2025-11-01T12:00:00Z'),
    published: true,
    visits: 322,
    submissions: 178,
  },
  {
    id: 'f-05',
    name: 'Event Registration – VanJS',
    description: 'RSVP and T-shirt size',
    createdAt: new Date('2025-10-05T18:45:00Z'),
    published: true,
    visits: 640,
    submissions: 512,
  },
  {
    id: 'f-06',
    name: 'Onboarding Checklist',
    description: 'Day-1 tasks',
    createdAt: new Date('2025-07-21T09:15:00Z'),
    published: false,
    visits: 41,
    submissions: 5,
  },
  {
    id: 'f-07',
    name: 'Feature Request',
    description: 'Prioritize roadmap ideas',
    createdAt: new Date('2025-09-28T16:10:00Z'),
    published: true,
    visits: 210,
    submissions: 73,
  },
  {
    id: 'f-08',
    name: 'Checkout – Beta',
    description: 'Test payment flow feedback',
    createdAt: new Date('2025-10-25T11:05:00Z'),
    published: true,
    visits: 480,
    submissions: 129,
  },
];

export const MOCK_FORM_STATS = {
  submissions: 1790,
  submissionRate: 32.5,
  bounceRate: 18.2,
  visits: 5500,
};
