export enum ModalId {
  RESEND_VERIFICATION_SUCCESS = 'resend-verification-success-modal',
  FORGOT_PASSWORD_SUCCESS = 'forgot-password-success-modal',
  RESET_PASSWORD_SUCCESS = 'reset-password-success-modal',
  REGISTER_SUCCESS = 'register-success-modal',
  CREATE_FORM = 'create-form-modal',
  SUBMIT_FORM = 'submit-form-modal',
  SUBMIT_PREVIEW = 'submit-preview-modal',
  SUBMIT_LEAD = 'submit-lead-modal',
  PAUSE_FORM = 'pause-form-modal',
  RESUME_FORM = 'resume-form-modal',
}

export enum ModalErrorType {
  RESENT_VERIFY_EMAIL_ERROR = 'resent-verify-email-error-modal',
  FORGOT_PASSWORD_ERROR = 'forgot-password-error-modal',
  RESET_PASSWORD_ERROR = 'reset-password-error-modal',
  REGISTER_ERROR = 'register-error-modal',
  CREATE_FORM_ERROR = 'create-form-error-modal',
  EMAIL_CONFIRMATION_ERROR = 'email-confirmation-error-modal',
  LOGIN_ERROR = 'login-error-modal',
  PUBLISH_FORM_ERROR = 'publish-form-error-modal',
  SUBMIT_LEAD_ERROR = 'submit-lead-error-modal',
  GET_SUBMISSIONS_ERROR = 'get-submissions-error-modal',
  GET_FORMS_ERROR = 'get-forms-error-modal',
  UPDATE_RENDER_MODE_ERROR = 'update-render-mode-error-modal',
  PAUSE_FORM_ERROR = 'pause-form-error-modal',
  RESUME_FORM_ERROR = 'resume-form-error-modal',
  SUBMIT_FORM_ERROR = 'submit-form-error-modal',
}
